apiVersion: passbolt.tagesspiegel.de/v1alpha1
kind: PassboltSecret
metadata:
  labels:
    app.kubernetes.io/name: passboltsecret
    app.kubernetes.io/instance: passboltsecret-sample
    app.kubernetes.io/part-of: kubernetes-passbolt-operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubernetes-passbolt-operator
  name: passboltsecret-sample
spec:
  # TODO(user): Add fields here
